In [1]:
import numpy as np

In [2]:
arr = np.array(['abc', 'defg'], dtype='U')
print(arr)
print(arr[0])
print(type(arr))
print(type(arr[0]))
print(arr.dtype)

['abc' 'defg']
abc
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<U4


In [6]:
arr = np.array(['abc', 'defg'], dtype='S')
print(arr)
print(arr[0])
print(type(arr))
print(type(arr[0]))
print(arr.dtype)
print(arr[0].decode('utf'))


[b'abc' b'defg']
b'abc'
<class 'numpy.ndarray'>
<class 'numpy.bytes_'>
|S4
abc


In [ ]:

arr_S = np.array(['a', 'b', 'c'], dtype='S')
arr_U = np.array(['a', 'b', 'c'], dtype='U')

print(arr_S.nbytes)   # smaller 3
print(arr_U.nbytes)   # larger 12


3
12


In [38]:
arr = np.arange(2*3*4*5*3).reshape(2, 3, 4, 5, 3)
print(arr.shape)
# print(arr)

print(arr[0].shape)        # (3, 4, 5, 3)
print(arr[0, 1].shape )    # (4, 5, 3)
print(arr[0, 1, 2].shape ) # (5, 3)
print(arr[0, 1, 2, 4].shape)  # (3,)



(2, 3, 4, 5, 3)
(3, 4, 5, 3)
(4, 5, 3)
(5, 3)
(3,)


In [45]:
from numpy import random

x = random.randint(100, size=(2,3))
y = random.rand(2,3, 1)

y, x

(array([[[0.00358535],
         [0.0658241 ],
         [0.35413374]],
 
        [[0.84287511],
         [0.66878405],
         [0.89050736]]]),
 array([[24,  2, 17],
        [32,  9, 40]], dtype=int32))

In [49]:
x = random.choice([3], size=(3,9))

print(x)

[[3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]]


In [57]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.5, 0.1], size=(100))

print(x)

[3 7 5 9 5 5 7 9 7 7 5 5 5 5 7 5 3 7 9 3 7 7 7 5 3 9 7 3 5 5 5 7 7 7 7 3 7
 7 7 7 5 7 7 7 5 9 7 7 5 5 7 5 7 5 5 9 7 5 3 9 5 7 9 3 5 3 5 5 5 7 7 7 3 5
 3 5 5 7 7 5 3 3 5 7 7 3 7 7 7 7 7 5 7 5 5 7 7 5 7 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 5 1 4 3]


In [65]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[3 1 5 4 2]
